define({
    root: {
        validation              : {
            require_captcha     : 'For security purpose you need input captcha to continue.',
            require_phone       : "Please choose your phone.",
            invalid_authentication
                                : 'invalid_authentication_msg',
            incorrect_captcha   : 'incorrect_captcha_msg',
            require_2factor     : 'Enter the verification code generated by your mobile application.',
            incorrect_2factor   : 'incorrect_2factor_msg',
            badpassword         : 'badpassword_msg',
            passwordmismatch    : 'passwordmismatch_msg',
            passwordhistory     : 'passwordhistory_msg',
            already_used        : 'You already use 2-step verification.',
            require_changepass  : 'You must change password before enable 2-step verification.',
            incorrect_email     : 'Your email is invalid.',
            resetexpired        : 'resetexpired',
            resetbadid          : 'resetbadid'
        },
        message                 : {
            twoFA_enable        : '2FA enable success msg',
            twoFA_disable       : '2FA disable success msg',
            new_password_sent   : 'new_password_sent',
            reset_password      : 'Your password has now been reset and emailed to you. Please check your email to find your new password.',
            choose_phone_top    : 'We only support a single Authenticator app configured for your account. Please select your new phone type:',
            choose_phone_bottom : 'Once you complete this setup, <strong>the codes generated by your old Authenticator app will stop working</strong>.'
        },
        box_title               : {
            login               : 'Sign In',
            captcha             : 'Captcha',
            twoFA               : '2-step verification',
            lost_password       : 'Lost Password'
        },
        button                  : {
            twoFA_trigger       : '2-step verification',
            twoFA_disable       : 'Disable 2factor',
            sign_in             : 'Sign in',
            prev                : 'Prev',
            verify              : 'Verify',
            verify_and_save     : 'Verify and Save',
            move_phone          : 'Move to a different phone',
            'continue'          : 'Continue',
            change_pass         : 'Change Password',
            remember_me         : 'Remember me',
            code                : 'Code',
            submit              : 'Submit',
            username            : 'Username',
            password            : 'Password',
            new_pass            : 'New Password',
            new_pass_confirm    : 'New Password Confirm',
            lost_password       : 'Lost Password',
            reset_password      : 'Reset Password',
            email               : 'eMail'
        },
        markdown_2factor        : {
            iphone              : '#####Install the Google Authenticator app for iPhone.\n\
\n\
- On your iPhone, tap the App Store icon.\n\
- Search for Google Authenticator.   \n\
([Download from the App Store]({{app_url}}))\n\
- Tap the app, and then tap Free to download and install it.\n\
\n\
#####Now open and configure Google Authenticator.\n\
\n\
- In Google Authenticator, tap "+", and then "Scan Barcode."\n\
- Use your phone\'s camera to scan this barcode.\n\
\n\
![QR Code]({{image_url}})\n\
\n\
Once you have scanned the barcode, enter the 6-digit verification code generated by the Authenticator app.',
            android             : '#####Install the Google Authenticator app for Android.\n\
\n\
- On your phone, go to the Google Play Store.\n\
- Search for Google Authenticator.   \n\
([Download from the Google Play Store]({{app_url}}))\n\
- Download and install the application.\n\
\n\
#####Now open and configure Google Authenticator.\n\
\n\
- In Google Authenticator, touch Menu and select "Set up account."\n\
- Select "Scan a barcode."\n\
- Use your phone\'s camera to scan this barcode.\n\
\n\
![QR Code]({{image_url}})\n\
\n\
Once you have scanned the barcode, enter the 6-digit verification code generated by the Authenticator app.',
            blackberry          : '#####Install the Google Authenticator app for BlackBerry\n\
\n\
- On your phone, open a web browser.\n\
- Go to *{{app_url}}*.\n\
- Download and install the Google Authenticator application.\n\
\n\
#####Now open and configure Google Authenticator.\n\
\n\
- In Google Authenticator, select Manual key entry.\n\
- In "Enter account name" type your full email address.\n\
- In "Enter key" type your secret key: ***{{secret_key}}***\n\
- Choose Time-based type of key.\n\
- Tap Save.\n\
\n\
Once you have scanned the barcode, enter the 6-digit verification code generated by the Authenticator app.',
        },
    },
    VN: true
});